version: '3'

services:
    db:
        container_name: ppsps_mysql_con
        image: mysql:5.6
        volumes:
            - ./var/logs/mysql:/var/log/mysql
            - ./database:/var/lib/mysql
        env_file:
            - ./.env.local
        environment:
            MYSQL_DATABASE: ppsps
    php:
        container_name: ppsps_php_con
        image: thecodingmachine/php:7.2-v2-apache
        build: .
        volumes:
            - .:/var/www/html/:rw
            - ./var/logs/php:/usr/local/etc/logs
            - ./var/cache/composer:/var/www/.composer/cache
            - ./docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./docker/server.crt:/etc/apache2/ssl/server.crt
            - ./docker/server.key:/etc/apache2/ssl/server.key
        links:
          - db:db
        env_file:
            - ./.env.local
        environment:
            APACHE_DOCUMENT_ROOT: public/
            PHP_INI_ERROR_REPORTING: E_ALL & ~E_NOTICE
            APP_ENV: dev
            PHP_EXTENSION_INTL: 1
            PHP_EXTENSION_SSL: 1
            PHP_INI_MEMORY_LIMIT: 2048M
            APACHE_EXTENSION_SSL: 1
            APACHE_EXTENSION_SOCACHE_SHMCB: 1
        ports:
            - 80:80
            - 443:443
    phpmyadmin:
        container_name: ppsps_phpmyadmin_con
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 9001:80
        links:
            - db:db
