[frontends]
  [frontends.default]
  backend = "default"
    [frontends.default.routes.host]
    rule = "Host:ppspsbyrougeot.com"

[backends]
  [backends.default]
      [backends.default.servers.default]
      url = "http://php:80"
