#!/bin/bash
set -e

# Symfony's coding standards tests
docker run --rm -v $PWD:/code:ro logomotion/code-quality phpcs --standard=PSR2 ./src &&

# php security checks
docker run --rm -v $PWD:/code:ro logomotion/code-quality security-checker security:check composer.lock &&